language: node_js
node_js:
  - '10'
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm ci
script:
  - npm test
  - $(npm bin)/cypress run --record
after_script: "cat ./coverage/lcov.info | coveralls"
